unlink("analysis/cache/about.Rmd", recursive = TRUE)
unlink("docs/figure/about.Rmd", recursive = TRUE)
unlink("docs/about.html")
wflow_build(files = "analysis/about.Rmd")
wflow_publish(files = "analysis/about.Rmd")

unlink("analysis/cache/index.Rmd", recursive = TRUE)
unlink("docs/figure/index.Rmd", recursive = TRUE)
unlink("docs/index.html")
wflow_build(files = "analysis/index.Rmd")
wflow_publish(files = "analysis/index.Rmd")

unlink("analysis/cache/license.Rmd", recursive = TRUE)
unlink("docs/figure/license.Rmd", recursive = TRUE)
unlink("docs/license.html")
wflow_build(files = "analysis/license.Rmd")
wflow_publish(files = "analysis/license.Rmd")

unlink("analysis/cache/01-batch-integration.Rmd", recursive = TRUE)
unlink("docs/figure/01-batch-integration.Rmd", recursive = TRUE)
unlink("output/01-batch-integration.rds")
unlink("docs/01-batch-integration.html")
wflow_build(files = "analysis/01-batch-integration.Rmd")
wflow_publish(files = "analysis/01-batch-integration.Rmd")

unlink("analysis/cache/02-atlas-integration.Rmd", recursive = TRUE)
unlink("docs/figure/02-atlas-integration.Rmd", recursive = TRUE)
unlink("output/02-atlas-integration.rds")
unlink("docs/02-atlas-integration.html")
wflow_build(files = "analysis/02-atlas-integration.Rmd")
wflow_publish(files = "analysis/02-atlas-integration.Rmd")

unlink("analysis/cache/03-human-integration.Rmd", recursive = TRUE)
unlink("docs/figure/03-human-integration.Rmd", recursive = TRUE)
unlink("output/03-human-integration.rds")
unlink("docs/03-human-integration.html")
wflow_build(files = "analysis/03-human-integration.Rmd")
wflow_publish(files = "analysis/03-human-integration.Rmd")

unlink("analysis/cache/interactive.Rmd", recursive = TRUE)
unlink("docs/figure/interactive.Rmd", recursive = TRUE)
unlink("output/interactive.rds")
unlink("docs/interactive.html")
wflow_build(files = "analysis/interactive.Rmd")
wflow_publish(files = "analysis/interactive.Rmd")
