# Step 1: Commit analysis files

system("git add analysis/about.Rmd")
system("git add analysis/index.Rmd")
system("git add analysis/license.Rmd")
system("git add analysis/01-batch-integration.Rmd")
system("git add analysis/02-reduced-dimensions.Rmd")
system("git add analysis/03-clustering.Rmd")
system("git add analysis/04-marker-detection.Rmd")
system("git add analysis/lineage-markers.Rmd")
# system("git add analysis/atlas-integration.Rmd")
# system("git add analysis/human-integration.Rmd")
#system("git add analysis/interactive.Rmd")
system("git commit -m 'Build'")

# Step 2: Build HTML files

wflow_build("analysis/about.Rmd")
wflow_build("analysis/index.Rmd")
wflow_build("analysis/license.Rmd")
wflow_build("analysis/01-batch-integration.Rmd")
wflow_build("analysis/02-reduced-dimensions.Rmd")
wflow_build("analysis/03-clustering.Rmd")
wflow_build("analysis/04-marker-detection.Rmd")
wflow_build("analysis/lineage-markers.Rmd")
# wflow_build("analysis/atlas-integration.Rmd")
# wflow_build("analysis/human-integration.Rmd")
#wflow_build("analysis/interactive.Rmd")

# Step 3: Commit HTML files

system("git add docs/about.html")
system("git add docs/index.html")
system("git add docs/license.html")
system("git add docs/01-batch-integration.html")
system("git add docs/02-reduced-dimensions.html")
system("git add docs/03-clustering.html")
system("git add docs/04-marker-detection.html")
system("git add docs/lineage-markers.html")
# system("git add docs/atlas-integration.html")
# system("git add docs/human-integration.html")
#system("git add docs/interactive.html")
system("git add docs/figure/01-batch-integration.Rmd")
system("git add docs/figure/02-reduced-dimensions.Rmd")
system("git add docs/figure/03-clustering.Rmd")
system("git add docs/figure/04-marker-detection.Rmd")
system("git add docs/figure/lineage-markers.Rmd")
# system("git add docs/figure/atlas-integration.Rmd")
# system("git add docs/figure/human-integration.Rmd")
system("git add docs/site_libs")
system("git add docs/.nojekyll")
system("git commit -m 'Build'")
system("git push origin master")
